### ISSUE TITLE
adopted/ca_uoguelph_ccs_sidebar/ does not show any event from "today" in shared calendar

### ISSUE THREAD

**Issue by mammut47** [Zimbra-Community/ca_uoguelph_ccs_sidebar#2]
recurring events are not shown in "today" sidebar.
single events are shown in "today" sidebar.
daily recurring events are shown in "tomorrow"

**Comment by ghost** [comment]
Please check:
https://github.com/Zimbra-Community/adopted/issues/38

**Comment by ghost** [comment]
Switching language does not help. Recurring events are not displayed in "today". Only recurring Events are not displayed. Single events are displayed.

**Comment by ghost** [comment]
I looked into it, and here repeating events are shown, see attached screenshots.

Events that are today, but have a time that is in the past, are not shown.

If you want to debug further, can you send me an export of the calendar that does not work (export via zimbra web interface).

Also make sure to use the correct version of the zimlet remove current installed version and:
git clone https://github.com/Zimbra-Community/ca_uoguelph_ccs_sidebar
and copy paste the 
ca_uoguelph_ccs_sidebar/ca_uoguelph_ccs_sidebar 
to
/opt/zimbra/zimlets-deployed/_dev/ca_uoguelph_ccs_sidebar

Then in your browser use ?dev=1 like:
https://server.com/?dev=1

Then hit f12 and use browser console to see if there are any error messages.

![1](https://cloud.githubusercontent.com/assets/4353213/13315559/ac0bf5f2-dbab-11e5-949e-fefe0d1a149c.png)
![2](https://cloud.githubusercontent.com/assets/4353213/13315560/ac0d4c86-dbab-11e5-9a96-a3b78c55e720.png)
![3](https://cloud.githubusercontent.com/assets/4353213/13315561/ac0dfe42-dbab-11e5-895e-dfe875fddf43.png)

**Comment by mammut47** [comment]
1. i deleted the zimlet via WEB-Admin-Console
2. git clone https://github.com/Zimbra-Community/ca_uoguelph_ccs_sidebar
3. copy the files to /opt/zimbra/zimlets-deployed/_dev/ca_uoguelph_ccs_sidebar
   Result:
4. In Zimbra Web-Admin-Console there is no Zimlet
   ![2016-02-29 07_57_08-zimbra-verwaltung - lxmail ova local](https://cloud.githubusercontent.com/assets/12047148/13387743/30bfad64-deba-11e5-9698-7c69db5e822d.png)
5. But within Webmail from User. there is the Zimlet shown.
   Recurring Events from opened User are shown. But no recurring Events from other Calendars are sometimes shown.
   ![1ova](https://cloud.githubusercontent.com/assets/12047148/13387869/69556456-debb-11e5-9e2e-51f21459fa3e.png)
   ![2oval](https://cloud.githubusercontent.com/assets/12047148/13387960/4030ce48-debc-11e5-96ff-b4f7ee912448.png)

I will send the exported ICS-File via Mail.
Many thanks for your help

**Comment by mammut47** [comment]
Hi, 
here the exported File for one Calendar. 
This calendar is not in my personal Account. 
Its in a central Account 

Manfred

**Comment by mammut47** [comment]
Here the missing file

**Comment by mammut47** [comment]
Without the "/?dev=1 i get following appearance
![3ova](https://cloud.githubusercontent.com/assets/12047148/13397735/87acee52-defb-11e5-971a-01b23618fc39.png)

**Comment by ghost** [comment]
Without ?dev it is normal you see question marks, it is something I really don't like about Zimbra.

Bug: https://bugzilla.zimbra.com/show_bug.cgi?id=97708

**Comment by ghost** [comment]
Today got around to test some more, here events in a shared calendar are displayed on the Zimlet so- it is supported.

Also it looks like the Zimlet does not care if the appointment is displayed as free or busy

![2016-03-10-122727_3840x1080_scrot](https://cloud.githubusercontent.com/assets/4353213/13668210/a49f0e42-e6bb-11e5-80d3-4672389ccfde.png)

I have not received that ics file you said you would send in your last update, so far I cannot reproduce your issue.

**Comment by mammut47** [comment]
Mark your event as whole Day event. Than its gone in "today"....

**Comment by ghost** [comment]
line 350:
(currentAppt.getStartTime() >= startTime) &&

Is the line that is causing this issue

**Comment by ghost** [comment]
For all day events the start time is always smaller than the current time, as basically the start time equals the moment when the day starts.

We need to add some code to see if the ALL DAY check is set, and skip the check on line 350

**Comment by ghost** [comment]
https://files.zimbra.com/docs/zimlet/zcs/8.6.0/jsapi-zimbra-doc/symbols/ZmCalBaseItem.html
 isAllDayEvent()

**Comment by ghost** [comment]
@mammut47 I just patched the github version to fix your issue, can you please verify that the zimlet works correct now, I will then upload a new version to Zimbra.org.

Thanks, Barry

You can make donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A

**Comment by mammut47** [comment]
It nearly works :-)
![ova-recurring-event local](https://cloud.githubusercontent.com/assets/12047148/13672754/5ea63e90-e6d6-11e5-9c57-657179a6ebcb.png)
Now one recurring Event is displayed more than once

**Comment by ghost** [comment]
Amazing, here it just displays the one. Can you PLEASE export your calendar and send it to info@barrydegraaff.tk

There must be another attribute that does this

**Comment by ghost** [comment]
Hmm, maybe that is a cache issue, as again I cannot reproduce that more than once issue

**Comment by ghost** [comment]
@mammut47  do you have multiple-day events, aka events that are > 24 hours?

**Comment by ghost** [comment]
I have received the ics files and indeed the appointment that shows up multiple times, is a single event that spans 5 days or so:

There is a rather complicated bug on thart:
http://bugzilla.zimbra.com/show_bug.cgi?id=80558

Lets see if I can fix this

**Comment by mammut47** [comment]
Its an old Bug in Zimbra itself?
There is no hurry. I will use the "old" Sidebar-Zimlet.

**Comment by ghost** [comment]
I am working on it now

**Comment by ghost** [comment]
@mammut47 I fixed the multiday issue now, can you please verfiy once more? Thanks!

![image](https://cloud.githubusercontent.com/assets/4353213/13697675/57ec0262-e76f-11e5-9c85-a3964604b05a.png)

**Comment by mammut47** [comment]
Now its working!!!
![2016-03-11 10_14_36-zimbra_ posteingang - lxmail ova local](https://cloud.githubusercontent.com/assets/12047148/13698099/36257930-e772-11e5-8a4a-3f08b0617beb.png)
Thank you very much!
